Create initial file
Baby-Yoda-RN/quiz-mobile pull request #17
Opened 2022-03-16 23:46 UTC by aahenry51

Starting the component.

2022-03-17 16:45 UTC, aahenry51 reviewed
Export of the ListContainer and the style

2022-03-17 22:04 UTC, mshago requested changes

2022-03-17 22:04 UTC, mshago commented on components/ListItem/ListItem.js
> +export default ListItem;
Do not export by default the component, if you do this you give the chance to renamed the component when is imported.

2022-03-17 23:04 UTC, raynesmike approved these changes

2022-03-17 23:04 UTC, raynesmike commented on index.js
>  import {name as appName} from './app.json';
So this is how you rename the import

2022-03-17 23:09 UTC, Josetf2396 commented
looks good will be adding to listviewscreen

2022-03-17 23:09 UTC, Josetf2396 approved these changes

2022-03-18 21:03 UTC, aahenry51 commented
![image](https://user-images.githubusercontent.com/79045258/159082769-b09ec12d-4337-4a8c-a586-e4988a34156b.png)

2022-03-19 19:12 UTC, aahenry51 commented
![image](https://user-images.githubusercontent.com/79045258/159135204-ce8ed970-87d1-4dfd-aa47-07f1dfe35def.png)

2022-03-22 00:03 UTC, raynesmike commented on src/components/ListItem/ListItem.Style.js
> +
Update this to refere the theme

2022-03-22 00:21 UTC, closed without merging