icons: created custom icons using react-native-vector-icons
Baby-Yoda-RN/quiz-mobile pull request #21
Opened 2022-03-18 22:19 UTC by Nap1400

Used FontAwesome5 library.

2022-03-18 22:56 UTC, Nap1400 commented
![icons](https://user-images.githubusercontent.com/68311219/159094750-f9fdbdc1-461b-4e4a-bdbc-fa99a3f9df4a.png)

2022-03-18 23:56 UTC, Dulaya approved these changes
I tried these code, and it works fine on my end.

2022-03-18 23:56 UTC, Dulaya commented on package.json
> +    "react-native-vector-icons": "^9.1.0"
Note: if you're using this component, you need to run `npx react-native link` to to let `react-native-vector-icons` library render icons properly.

2022-03-18 23:56 UTC, Dulaya commented on src/components/icon/Icon.js
> +    console.log(styles);
Maybe get rid of console.log().

2022-03-19 00:22 UTC, lasharela requested changes

2022-03-19 00:22 UTC, lasharela commented on src/components/icon/Icon.js
> +  </View>
never ever use inline styles.

2022-03-19 00:22 UTC, lasharela commented on src/components/icon/Icon.style.js
> +    small: 40,
not relevant JSS. inside of styleSheet keep styles.

2022-03-19 15:19 UTC, lasharela approved these changes

2022-03-19 16:50 UTC, raynesmike approved these changes
Everything seem to work with the icons when on the top section

2022-03-19 16:50 UTC, merged