ListView: created list view with sample data
Baby-Yoda-RN/quiz-mobile pull request #23
Opened 2022-03-19 17:23 UTC by carizzuti

I created a list view component with default/sample data using names

![image](https://user-images.githubusercontent.com/61713261/159131585-fd497436-8206-4b88-a4fc-5a7559bfa87e.png)

2022-03-19 17:55 UTC, raynesmike commented on src/components/listView/ListView.js
> +
Looks great, im assuming we will be getting all this data from the backend

2022-03-19 17:55 UTC, raynesmike approved these changes
looks great with all the additions,

2022-03-19 18:51 UTC, lasharela requested changes

2022-03-19 18:51 UTC, lasharela commented on src/screens/dashboard/DashboardScreen.js
>  import {Icon} from '../../components/icon/Icon'
Import from index

2022-03-19 18:51 UTC, lasharela commented on src/screens/dashboard/DashboardScreen.js
> +import { ListView } from '../../components/listView/ListView';
From index

2022-03-19 22:35 UTC, mshago approved these changes

2022-03-20 22:40 UTC, Dulaya approved these changes
Looks okay. We'll put it together.

2022-03-20 23:57 UTC, merged