"StepsProgress component tracks the current step and the total number of steps"
Baby-Yoda-RN/quiz-mobile pull request #32
Opened 2022-03-22 19:40 UTC by Nap1400

2022-03-22 23:48 UTC, raynesmike approved these changes

2022-03-22 23:48 UTC, raynesmike commented on src/components/stepsProgress/StepsProgress.js
> +        throw console.error('Value for totalSteps required');
lets also check for totalSteps=0

2022-03-23 07:26 UTC, Dulaya commented
Also are you not using styling at all?

2022-03-23 07:26 UTC, Dulaya requested changes

2022-03-23 07:26 UTC, Dulaya commented on src/components/stepsProgress/StepsProgress.js
> +    if (totalSteps === null || totalSteps === undefined){
I think this checks for more condition: `if(!totalSteps && !Number.isInteger(totalSteps))`

2022-03-23 21:01 UTC, Dulaya approved these changes
Went over with Nicholas on video call to get issues fixed. Works fine.

2022-03-23 21:15 UTC, lasharela approved these changes

2022-03-23 21:30 UTC, merged