PENDING: Fetch Data
Baby-Yoda-RN/quiz-mobile pull request #39
Opened 2022-03-23 20:31 UTC by leo-he-1

2022-03-23 21:22 UTC, leo-he-1 commented
![screenshotdata](https://user-images.githubusercontent.com/70768391/159797938-2a9127c7-1450-48c1-94e7-7b998175d751.png)

2022-03-23 22:13 UTC, Dulaya commented
1. Remove the quotes in useState. Just leave it empty.
2. Change the state name and function name to something more meaningful like this: `const [tests, setTests] = useState();`
3. Use `useEffect` hook. This will request data online one time. Notice `useState` request data multiple times and may overload the server. Also notice I sorted the tests by id. DynamoDB returned unsorted tests.
`  useEffect( () => {
     Axios.post(url, body).then (({data}) => {
      const returnData = data.Items;
      const sortData = returnData.sort((firstItem, secondItem) => firstItem.id - secondItem.id);
      setData(sortData);
    }).catch(error => console.error(error))
  }, []);`

![image](https://user-images.githubusercontent.com/50040948/159804764-3a1d1cc0-73ba-4849-994b-5df09b15edd3.png)

2022-03-23 22:13 UTC, Dulaya requested changes
See my comments.

2022-03-23 23:19 UTC, raynesmike commented on src/components/listView/ListView.js
> +  const [data, setData] = useState("stuff");
You dont need to set useState I think. Just make it empty so useState()

2022-03-23 23:19 UTC, lasharela requested changes

2022-03-23 23:19 UTC, lasharela commented on src/components/listView/ListView.js
> +  Axios.post (url, body, {
post is to do some action on the server side. to get data, we have to have a `get` endpoint. most probably this is to @Dulaya. but for now we can merge as it is.

2022-03-23 23:19 UTC, lasharela commented on src/components/listView/ListView.js
> +    console.log('Error');d
; d - this letter feels as error.  and instead of `Error` as string you can console log `error` variable and you'll see actual error

2022-03-24 02:54 UTC, Dulaya approved these changes

2022-03-24 18:55 UTC, Nap1400 approved these changes

2022-03-25 14:01 UTC, raynesmike commented on src/components/listView/ListView.js
> +    setIsLoading(true);
i think you can remove line 13 if you set useState() which sets isLoading as a truthy value.

2022-03-25 22:58 UTC, carizzuti approved these changes
Looks good, helped me with using Axios too

2022-03-25 23:38 UTC, raynesmike approved these changes
I approve this changes, I learned a lot from this

2022-03-26 15:00 UTC, raynesmike approved these changes

2022-03-27 03:17 UTC, merged