PENDING: Jose/backButtonFunction
Baby-Yoda-RN/quiz-mobile pull request #65
Opened 2022-04-01 19:57 UTC by Josetf2396

Had some problems with git the file I changes isn't showing up

2022-04-01 21:58 UTC, lasharela approved these changes

2022-04-01 22:02 UTC, Dulaya approved these changes
I don't see any issues with this. However, I'm still confused whether the back button should take the user to the Dashboard or previous questions.

2022-04-01 22:50 UTC, aahenry51 approved these changes

2022-04-01 22:59 UTC, raynesmike approved these changes

2022-04-02 00:05 UTC, lasharela requested changes

2022-04-02 00:05 UTC, lasharela commented on src/screens/detail/DetailScreen.js
>    const onPress = () => {};
Remove

2022-04-05 02:13 UTC, Dulaya commented
I'm gonna approve this since I need it to test the questions changing.

2022-04-05 02:14 UTC, merged